### ISSUE TITLE
sampling or model issue makes jagged pattern on some models

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#84]
one more issue is timer doesnt count time
![issue1](https://github.com/user-attachments/assets/59acb602-7ce3-42e2-b748-911b6a08745b)
![issue2](https://github.com/user-attachments/assets/d4f7fc6f-a941-44d7-9d7d-3bc2c54ab673)

**Comment by gameknife** [comment]
seems like you prefer a "progressive rendering on frame" mode, currently the all effort is targeting realtime rendering. this issue is not notice on 16-32 tempral frames.

may be the progressive rendering mode should like the origin "RayTracing in OneWeekend" repo, introduce a float64 accumlate buffer instead off current temporal buffer?

**Comment by tigrazone** [comment]
I use unchanged your repository. Maybe problem with models

**Comment by gameknife** [comment]
corner hit may generate wrong normal, add epsilon to fix it.
fixed in https://github.com/gameknife/gkNextRenderer/commit/ae8b5ee641eedb4287ac7a49342a5553871a8c16
